### ISSUE TITLE
The table of functions by name is broken.

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb-docs#99]
http://orientdb.com/docs/2.1/SQL-Functions.html#functions-by-name

Scott

**Comment by santo-it** [comment]
Hi @smolinari ,

Thanks for opening this issue

From the description I can't understand well the issue you saw, but I have anyway pushed a possible fix in the master branch

Could you check if this fixes the issue you were seeing - or please could you describe better the issue

You can see the difference here:

- master (with the fix I pushed): http://orientdb.com/docs/master/SQL-Functions.html#functions-by-name
- 2.2. branch (without the fix): http://orientdb.com/docs/2.2/SQL-Functions.html#functions-by-name

I think the problem was an additional and not needed column in the table (?), or perhaps the empty header row (?)

Many thanks,

**Comment by smolinari** [comment]
Oh. you know what? So sorry. But, this issue was actually fixed. There was a similar problem with the methods table too. Basically, the problem was that when you clicked on one of the functions in the table, the browser didn't move to the respective anchor. That problem is gone. Closing this. 

Scott

**Comment by santo-it** [comment]
Okay. Not a problem at all. Thanks to you for opening issues. I noticed there are a few more issues from you and I'll try to comment on those asap. Your feedback is always appreciated and useful. Keep up the good work

Thanks,

**Comment by smolinari** [comment]
Do you work for ODB @santo-it ?

Scott

**Comment by santo-it** [comment]
yes :)

**Comment by smolinari** [comment]
Cool. Nice to see they have someone dedicated to the docs too. 

One of the things lacking explanation, but is a really powerful part of ODB, is the custom functions and triggers.  Also there needs to be a lot more real world and in depth examples of queries. From my experience the most asked question is "how do I query this in ODB?" More examples of queries would help alleviate that lack of knowledge. 😄 

Scott
